// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTw6x9XRYyCQCcZauGUvM2i11eYTGD4Rs',
    appId: '1:446629770923:web:04103b0467c897e62469ee',
    messagingSenderId: '446629770923',
    projectId: 'etegram-sales-app',
    authDomain: 'etegram-sales-app.firebaseapp.com',
    storageBucket: 'etegram-sales-app.firebasestorage.app',
    measurementId: 'G-2PD4545Z9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92dgaQ95Wx0hysZ1MLHTQuIo_VuXxH_A',
    appId: '1:446629770923:android:216a2d8c8fd2ee1d2469ee',
    messagingSenderId: '446629770923',
    projectId: 'etegram-sales-app',
    storageBucket: 'etegram-sales-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZO7_ShUvWl2qY2qcAnCkoHy6BVKA6H_k',
    appId: '1:446629770923:ios:bae22bf4646945882469ee',
    messagingSenderId: '446629770923',
    projectId: 'etegram-sales-app',
    storageBucket: 'etegram-sales-app.firebasestorage.app',
    iosBundleId: 'com.etegramsales.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZO7_ShUvWl2qY2qcAnCkoHy6BVKA6H_k',
    appId: '1:446629770923:ios:35dc2681a20d878d2469ee',
    messagingSenderId: '446629770923',
    projectId: 'etegram-sales-app',
    storageBucket: 'etegram-sales-app.firebasestorage.app',
    iosBundleId: 'com.etegram.etegramBusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTw6x9XRYyCQCcZauGUvM2i11eYTGD4Rs',
    appId: '1:446629770923:web:55067c9bd6c49ce92469ee',
    messagingSenderId: '446629770923',
    projectId: 'etegram-sales-app',
    authDomain: 'etegram-sales-app.firebaseapp.com',
    storageBucket: 'etegram-sales-app.firebasestorage.app',
    measurementId: 'G-BENXSVS3T0',
  );
}
